// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/contracts/pr_repo_contract.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	api "github.com/AlexVashchenkov/avito-pr-reviewer-service/api"
	gomock "github.com/golang/mock/gomock"
)

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// CreatePullRequest mocks base method.
func (m *MockPullRequestRepository) CreatePullRequest(pr *api.PullRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreatePullRequest", pr)
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockPullRequestRepositoryMockRecorder) CreatePullRequest(pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockPullRequestRepository)(nil).CreatePullRequest), pr)
}

// GetPullRequest mocks base method.
func (m *MockPullRequestRepository) GetPullRequest(id string) (*api.PullRequest, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequest", id)
	ret0, _ := ret[0].(*api.PullRequest)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetPullRequest indicates an expected call of GetPullRequest.
func (mr *MockPullRequestRepositoryMockRecorder) GetPullRequest(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequest", reflect.TypeOf((*MockPullRequestRepository)(nil).GetPullRequest), id)
}

// GetPullRequestsByUser mocks base method.
func (m *MockPullRequestRepository) GetPullRequestsByUser(userID string) []api.PullRequestShort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestsByUser", userID)
	ret0, _ := ret[0].([]api.PullRequestShort)
	return ret0
}

// GetPullRequestsByUser indicates an expected call of GetPullRequestsByUser.
func (mr *MockPullRequestRepositoryMockRecorder) GetPullRequestsByUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestsByUser", reflect.TypeOf((*MockPullRequestRepository)(nil).GetPullRequestsByUser), userID)
}

// UpdatePullRequest mocks base method.
func (m *MockPullRequestRepository) UpdatePullRequest(pr *api.PullRequest) (*api.PullRequest, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullRequest", pr)
	ret0, _ := ret[0].(*api.PullRequest)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// UpdatePullRequest indicates an expected call of UpdatePullRequest.
func (mr *MockPullRequestRepositoryMockRecorder) UpdatePullRequest(pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullRequest", reflect.TypeOf((*MockPullRequestRepository)(nil).UpdatePullRequest), pr)
}
