// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/contracts/team_repo_contract.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	api "github.com/AlexVashchenkov/avito-pr-reviewer-service/api"
	gomock "github.com/golang/mock/gomock"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockTeamRepository) CreateTeam(team *api.Team) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateTeam", team)
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamRepositoryMockRecorder) CreateTeam(team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeamRepository)(nil).CreateTeam), team)
}

// GetTeamByName mocks base method.
func (m *MockTeamRepository) GetTeamByName(name string) (*api.Team, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByName", name)
	ret0, _ := ret[0].(*api.Team)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetTeamByName indicates an expected call of GetTeamByName.
func (mr *MockTeamRepositoryMockRecorder) GetTeamByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByName", reflect.TypeOf((*MockTeamRepository)(nil).GetTeamByName), name)
}

// UpdateTeam mocks base method.
func (m *MockTeamRepository) UpdateTeam(team *api.Team) (*api.Team, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeam", team)
	ret0, _ := ret[0].(*api.Team)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// UpdateTeam indicates an expected call of UpdateTeam.
func (mr *MockTeamRepositoryMockRecorder) UpdateTeam(team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeam", reflect.TypeOf((*MockTeamRepository)(nil).UpdateTeam), team)
}

// UpdateTeamMember mocks base method.
func (m *MockTeamRepository) UpdateTeamMember(user *api.User) (*api.User, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeamMember", user)
	ret0, _ := ret[0].(*api.User)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// UpdateTeamMember indicates an expected call of UpdateTeamMember.
func (mr *MockTeamRepositoryMockRecorder) UpdateTeamMember(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeamMember", reflect.TypeOf((*MockTeamRepository)(nil).UpdateTeamMember), user)
}
