// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAdminToken handles AdminToken security.
	HandleAdminToken(ctx context.Context, operationName OperationName, t AdminToken) (context.Context, error)
	// HandleUserToken handles UserToken security.
	HandleUserToken(ctx context.Context, operationName OperationName, t UserToken) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesAdminToken = map[string][]string{
	PullRequestCreatePostOperation:   []string{},
	PullRequestMergePostOperation:    []string{},
	PullRequestReassignPostOperation: []string{},
	TeamGetGetOperation:              []string{},
	UsersGetReviewGetOperation:       []string{},
	UsersSetIsActivePostOperation:    []string{},
}

func (s *Server) securityAdminToken(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t AdminToken
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesAdminToken[operationName]
	rctx, err := s.sec.HandleAdminToken(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

var operationRolesUserToken = map[string][]string{
	TeamGetGetOperation:        []string{},
	UsersGetReviewGetOperation: []string{},
}

func (s *Server) securityUserToken(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t UserToken
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesUserToken[operationName]
	rctx, err := s.sec.HandleUserToken(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// AdminToken provides AdminToken security value.
	AdminToken(ctx context.Context, operationName OperationName) (AdminToken, error)
	// UserToken provides UserToken security value.
	UserToken(ctx context.Context, operationName OperationName) (UserToken, error)
}

func (s *Client) securityAdminToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.AdminToken(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"AdminToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
func (s *Client) securityUserToken(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.UserToken(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"UserToken\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
